services:
    web:
        build:
            context: .
        container_name: batchcooking-web
        restart: unless-stopped
        command:
            [
                "/app/.venv/bin/fastapi",
                "dev",
                "app/main.py",
                "--host",
                "0.0.0.0",
                "--port",
                "80",
            ]
        volumes:
            - .:/app
            - /app/.venv
        ports:
            - "8002:80"
        env_file:
            - .env
        depends_on:
            - db

    db:
        image: postgres:16
        container_name: batchcooking-db
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5436:5432"
        env_file:
            - .env

volumes:
    postgres_data:
