services:
    web:
        build:
            context: .
        container_name: batchcooking-web
        restart: unless-stopped
        command:
            [
                "/app/.venv/bin/fastapi",
                "dev",
                "app/main.py",
                "--host",
                "0.0.0.0",
                "--port",
                "80",
            ]
        volumes:
            - .:/app
            - /app/.venv
        ports:
            - "8002:80"
        env_file:
            - .env
